# Generated by Django 4.1.5 on 2023-01-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=122)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
