# Generated by Django 4.1.5 on 2023-02-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_table',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=45)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_pass', models.CharField(max_length=200, unique=True)),
                ('customer_address', models.CharField(max_length=300)),
                ('customer_pin', models.IntegerField(default=0)),
                ('customer_phone', models.CharField(max_length=14)),
            ],
            options={
                'db_table': 'customer_table',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('item_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('c_item_id', models.CharField(max_length=30)),
                ('item_name', models.CharField(max_length=50)),
                ('item_image', models.ImageField(upload_to='uploads/images')),
                ('item_categories', models.CharField(max_length=30)),
                ('item_detail', models.CharField(max_length=300)),
                ('item_cost', models.IntegerField()),
                ('item_revenue', models.IntegerField()),
                ('shop_pin', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Shop_table',
            fields=[
                ('shop_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=45)),
                ('shop_email', models.EmailField(max_length=254)),
                ('shop_pass', models.CharField(max_length=200, unique=True)),
                ('shop_address', models.CharField(max_length=300)),
                ('shop_phone', models.CharField(max_length=14)),
                ('shop_alt', models.CharField(max_length=14)),
                ('shop_pin', models.IntegerField()),
                ('shop_ordered', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'shop_table',
            },
        ),
        migrations.CreateModel(
            name='Query_table',
            fields=[
                ('placing_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('item_cost', models.IntegerField()),
                ('item_revenue', models.IntegerField()),
                ('order_date', models.DateField()),
                ('order_status', models.CharField(max_length=100)),
                ('transcation_id', models.CharField(max_length=200)),
                ('customer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.customer_table', verbose_name='customer')),
                ('item_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.product', verbose_name='item')),
                ('shop_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.shop_table', verbose_name='shop')),
            ],
            options={
                'db_table': 'query_table',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shop_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.shop_table', verbose_name='placer'),
        ),
    ]
